-- Seed data for SkillGap
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Python', 'Language', 'py', 'https://docs.python.org/3/tutorial/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('JavaScript', 'Language', 'js,ecmascript,es6', 'https://javascript.info/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('TypeScript', 'Language', 'ts', 'https://www.typescriptlang.org/docs/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Java', 'Language', '', 'https://dev.java/learn/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('C++', 'Language', 'cpp', 'https://www.learncpp.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('SQL', 'Database', 'mysql,postgresql,postgres,sqlite,t-sql', 'https://sqlbolt.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('HTML', 'Frontend', 'html5', 'https://developer.mozilla.org/docs/Learn/HTML');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('CSS', 'Frontend', 'css3,scss,sass', 'https://developer.mozilla.org/docs/Learn/CSS');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('React', 'Frontend', 'react.js,reactjs', 'https://react.dev/learn');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Angular', 'Frontend', 'angularjs', 'https://angular.dev/tutorials');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Vue', 'Frontend', 'vue.js,vuejs', 'https://vuejs.org/tutorial/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Tailwind CSS', 'Frontend', 'tailwind', 'https://tailwindcss.com/docs');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Node.js', 'Backend', 'node,nodejs', 'https://nodejs.org/en/learn');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Express', 'Backend', 'express.js,expressjs', 'https://expressjs.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Django', 'Backend', '', 'https://docs.djangoproject.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Flask', 'Backend', '', 'https://flask.palletsprojects.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('FastAPI', 'Backend', '', 'https://fastapi.tiangolo.com/tutorial/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Spring Boot', 'Backend', 'spring framework', 'https://spring.io/guides');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('REST API', 'Backend', 'restful,rest apis,restful api,rest api', 'https://restfulapi.net/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('GraphQL', 'Backend', '', 'https://graphql.org/learn/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('MongoDB', 'Database', 'mongo', 'https://learn.mongodb.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('PostgreSQL', 'Database', 'postgres', 'https://www.postgresqltutorial.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Redis', 'Database', '', 'https://redis.io/docs/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Git', 'Tools', 'github,gitlab,version control', 'https://git-scm.com/book');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Docker', 'DevOps', 'containers,containerization', 'https://docs.docker.com/get-started/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Kubernetes', 'DevOps', 'k8s', 'https://kubernetes.io/docs/tutorials/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('AWS', 'Cloud', 'amazon web services,ec2,s3', 'https://aws.amazon.com/training/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Azure', 'Cloud', 'microsoft azure', 'https://learn.microsoft.com/training/azure/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Google Cloud', 'Cloud', 'gcp', 'https://cloud.google.com/learn');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('CI/CD', 'DevOps', 'jenkins,github actions,continuous integration,gitlab ci', 'https://docs.github.com/actions');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Linux', 'Tools', 'unix,bash,shell scripting', 'https://linuxjourney.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Terraform', 'DevOps', 'infrastructure as code,iac', 'https://developer.hashicorp.com/terraform/tutorials');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Pandas', 'Data', '', 'https://pandas.pydata.org/docs/getting_started/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('NumPy', 'Data', '', 'https://numpy.org/learn/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Machine Learning', 'Data', 'ml', 'https://www.coursera.org/learn/machine-learning');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Deep Learning', 'Data', 'neural networks', 'https://www.deeplearning.ai/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('TensorFlow', 'Data', '', 'https://www.tensorflow.org/tutorials');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('PyTorch', 'Data', '', 'https://pytorch.org/tutorials/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Scikit-learn', 'Data', 'sklearn,scikit learn', 'https://scikit-learn.org/stable/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Data Visualization', 'Data', 'matplotlib,seaborn,plotly', 'https://www.data-to-viz.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Statistics', 'Data', 'statistical analysis,hypothesis testing', 'https://www.khanacademy.org/math/statistics-probability');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Tableau', 'Data', '', 'https://www.tableau.com/learn/training');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Power BI', 'Data', 'powerbi', 'https://learn.microsoft.com/power-bi/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Excel', 'Data', 'microsoft excel,spreadsheets', 'https://support.microsoft.com/excel');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Data Structures', 'Fundamentals', 'algorithms,dsa,data structures and algorithms', 'https://www.geeksforgeeks.org/data-structures/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('OOP', 'Fundamentals', 'object oriented programming,object-oriented', 'https://www.freecodecamp.org/news/object-oriented-programming-concepts/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('System Design', 'Fundamentals', 'distributed systems,scalability', 'https://github.com/donnemartin/system-design-primer');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Unit Testing', 'Tools', 'jest,pytest,junit,test driven development,tdd', 'https://testing-library.com/docs/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Agile', 'Soft Skill', 'scrum,kanban', 'https://www.atlassian.com/agile');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Communication', 'Soft Skill', 'presentation skills,written communication', 'https://www.coursera.org/learn/wharton-communication-skills');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Problem Solving', 'Soft Skill', 'analytical skills,critical thinking', 'https://www.coursera.org/learn/problem-solving');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Teamwork', 'Soft Skill', 'collaboration,team player', 'https://www.coursera.org/learn/teamwork-skills-effective-communication');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Project Management', 'Soft Skill', 'jira,project planning,stakeholder management', 'https://www.atlassian.com/work-management/project-management');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Figma', 'Design', 'ui design,ux design,wireframing,prototyping', 'https://help.figma.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('SEO', 'Marketing', 'search engine optimization', 'https://developers.google.com/search/docs/fundamentals/seo-starter-guide');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Google Analytics', 'Marketing', 'web analytics', 'https://skillshop.withgoogle.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Content Writing', 'Marketing', 'copywriting,content marketing', 'https://academy.hubspot.com/courses/content-marketing');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Cybersecurity', 'Security', 'network security,penetration testing,owasp', 'https://tryhackme.com/');
INSERT OR IGNORE INTO skills (name, category, aliases, resource) VALUES ('Networking', 'Security', 'tcp/ip,dns', 'https://www.cloudflare.com/learning/');

INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Full Stack Developer', 'Builds both the user-facing and server-side parts of web apps.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Frontend Developer', 'Builds responsive, accessible user interfaces.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Backend Developer', 'Designs APIs, services and data layers.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Data Scientist', 'Extracts insights and builds predictive models from data.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Data Analyst', 'Turns data into reports and dashboards for decision making.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Machine Learning Engineer', 'Productionises ML models at scale.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('DevOps Engineer', 'Automates build, deployment and infrastructure.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Java Developer', 'Builds enterprise applications on the JVM.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('UI/UX Designer', 'Designs intuitive, user-centred product experiences.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Digital Marketer', 'Grows audiences and conversions through online channels.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Cybersecurity Analyst', 'Detects and prevents security threats.');
INSERT OR IGNORE INTO job_roles (title, description) VALUES ('Project Manager', 'Plans, tracks and delivers projects with cross-functional teams.');

INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='JavaScript'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='HTML'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='CSS'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='React'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='Node.js'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='SQL'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='REST API'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='Git'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='TypeScript'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='MongoDB'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='Docker'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='AWS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='Unit Testing'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='CI/CD'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Full Stack Developer'), (SELECT id FROM skills WHERE name='Agile'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='HTML'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='CSS'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='JavaScript'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='React'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='Git'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='REST API'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='TypeScript'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='Tailwind CSS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='Unit Testing'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='Figma'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='Vue'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Frontend Developer'), (SELECT id FROM skills WHERE name='Angular'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Python'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='SQL'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='REST API'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Git'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Data Structures'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Docker'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Node.js'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Django'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='FastAPI'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Redis'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='PostgreSQL'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='AWS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='Unit Testing'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='System Design'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Backend Developer'), (SELECT id FROM skills WHERE name='CI/CD'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Python'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='SQL'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Pandas'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='NumPy'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Machine Learning'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Statistics'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Data Visualization'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Scikit-learn'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='TensorFlow'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='PyTorch'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Deep Learning'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Tableau'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='Git'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Scientist'), (SELECT id FROM skills WHERE name='AWS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='SQL'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Excel'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Data Visualization'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Statistics'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Communication'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Python'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Pandas'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Tableau'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Power BI'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Data Analyst'), (SELECT id FROM skills WHERE name='Problem Solving'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Python'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Machine Learning'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Deep Learning'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Data Structures'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Git'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Docker'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='PyTorch'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='TensorFlow'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Scikit-learn'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='AWS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='Kubernetes'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='CI/CD'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Machine Learning Engineer'), (SELECT id FROM skills WHERE name='System Design'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Linux'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Docker'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Kubernetes'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='CI/CD'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Git'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='AWS'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Terraform'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Python'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Networking'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Azure'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Google Cloud'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='DevOps Engineer'), (SELECT id FROM skills WHERE name='Cybersecurity'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Java'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Spring Boot'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='SQL'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='OOP'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Git'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='REST API'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Data Structures'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Docker'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Unit Testing'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='AWS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Kubernetes'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='System Design'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Java Developer'), (SELECT id FROM skills WHERE name='Agile'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='Figma'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='Communication'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='Problem Solving'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='Teamwork'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='HTML'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='CSS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='Agile'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='UI/UX Designer'), (SELECT id FROM skills WHERE name='Project Management'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='SEO'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Google Analytics'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Content Writing'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Communication'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Excel'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Project Management'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Teamwork'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Digital Marketer'), (SELECT id FROM skills WHERE name='Data Visualization'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Cybersecurity'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Networking'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Linux'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Problem Solving'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Python'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='AWS'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Docker'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Communication'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Cybersecurity Analyst'), (SELECT id FROM skills WHERE name='Git'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Project Management'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Agile'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Communication'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Teamwork'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Problem Solving'), 'required');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Excel'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Power BI'), 'preferred');
INSERT OR IGNORE INTO job_skills (role_id, skill_id, importance) VALUES ((SELECT id FROM job_roles WHERE title='Project Manager'), (SELECT id FROM skills WHERE name='Git'), 'preferred');
